### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by kwaimind** [kwaimind/vancouver-freelancers#1]
More details needed on how the app works, as well as how to add more locations.

**Comment by praveen-me** [comment]
Can I work on this?
Can you tell me how to add more location for what?

**Comment by Ishaan28malik** [comment]
ok after forking what's the next step ?
and what else do i need to do ?

**Comment by kwaimind** [comment]
See my previous comment. Take a look at the `https://github.com/kwaimind/vancouver-freelancers/blob/master/src/components/leaflet.js` component, understand how locations are added, and then write a simple guide for the README.md.

**Comment by praveen-me** [comment]
Thanks, So can I start work on it.

**Comment by praveen-me** [comment]
Hey, @kwaimind I install gatsby by when I want to build it says **surge** not found.

**Comment by kwaimind** [comment]
You can ignore that. It's for deploying to production. Just run `gatsby develop` as normal
