### ISSUE TITLE
Improve CSS styling of the marker popups

### ISSUE THREAD

**Issue by kwaimind** [kwaimind/vancouver-freelancers#2]
Currently, when a user clicks on a popup marker, it displays the location info. I'd like to see this cleaned up so:

- the font is smaller and less intense
- the mobile experience is clean
- the UI is more app-like and less hacky

Check the components for the current emotion styling.

**Comment by SergioJrDev** [comment]
Hi, @kwaimind. I'll do that!

**Comment by SergioJrDev** [comment]
@kwaimind, before I submit my PR, let me know what you think with this popup style. Should I change any thing else? And another question; what mean the `/10` below the text?
![captura de tela 2018-10-02 as 15 59 14](https://user-images.githubusercontent.com/19225674/46370590-50d18780-c65c-11e8-8353-17a4730c945d.png)

**Comment by kwaimind** [comment]
That's really nice. The /10 was a rating from Foursquare but we can leave that out for now.

Can you make the close button a bit smaller please? Like 50% smaller.

Otherwise, great work!

**Comment by SergioJrDev** [comment]
@kwaimind I could not run the test environment in my machine, I think it is a gatsby config, but I changed the style and open a PR, if you can run in your machine to check it, i'll be appreciated.
https://github.com/kwaimind/vancouver-freelancers/pull/4

**Comment by kwaimind** [comment]
Great job @SergioJrDev . Closing now. Will add you to the credits footer too :) .
